CREATE DATABASE DB_NEW_LOCARE;

USE DB_NEW_LOCARE;

-- -----------------------------------------------------
-- Table TB_CIDADES
-- -----------------------------------------------------
CREATE TABLE TB_CIDADES (
  CID_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CID_CIDADE VARCHAR(20) NOT NULL,
  PRIMARY KEY (CID_CODIGO) 
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_BAIRROS
-- -----------------------------------------------------
CREATE TABLE TB_BAIRROS (
  BAI_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  BAI_BAIRRO VARCHAR(20) NOT NULL,
  BAI_CID_CODIGO INT UNSIGNED NOT NULL,
  PRIMARY KEY (BAI_CODIGO),
  FOREIGN KEY (BAI_CID_CODIGO) REFERENCES TB_CIDADES (CID_CODIGO)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table TB_MARCAS
-- -----------------------------------------------------
CREATE TABLE TB_MARCAS (
  MAR_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  MAR_MARCA VARCHAR(20) NOT NULL,
  PRIMARY KEY (MAR_CODIGO) 
)ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_CORES
-- -----------------------------------------------------
CREATE TABLE TB_CORES (
  COR_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  COR_COR VARCHAR(20) NOT NULL,
  PRIMARY KEY (COR_CODIGO) 
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_ESTADOS_CONSERVACAO
-- -----------------------------------------------------
CREATE TABLE TB_ESTADOS_CONSERVACAO (
  EST_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  EST_ESTADO VARCHAR(20) NOT NULL,
  PRIMARY KEY (EST_CODIGO) 
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_CARROS
-- -----------------------------------------------------
CREATE TABLE TB_CARROS (
  CAR_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CAR_MODELO VARCHAR(20) NOT NULL,
  CAR_ANO INT NOT NULL,
  CAR_ALUGUEL DECIMAL(5,2) UNSIGNED NOT NULL,
  CAR_MAR_CODIGO INT UNSIGNED NOT NULL,
  CAR_COR_CODIGO INT UNSIGNED NOT NULL,
  CAR_EST_CODIGO INT UNSIGNED NOT NULL,
  CAR_DISPONIVEL ENUM('s', 'n') NOT NULL DEFAULT 's',
  PRIMARY KEY (CAR_CODIGO),
  FOREIGN KEY (CAR_MAR_CODIGO) REFERENCES TB_MARCAS (MAR_CODIGO),
  FOREIGN KEY (CAR_COR_CODIGO) REFERENCES TB_CORES (COR_CODIGO),
  FOREIGN KEY (CAR_EST_CODIGO) REFERENCES TB_ESTADOS_CONSERVACAO (EST_CODIGO)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table TB_CLIENTES
-- -----------------------------------------------------
CREATE TABLE TB_CLIENTES (
  CLI_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  CLI_NOME VARCHAR(80) NOT NULL,
  CLI_BAI_CODIGO INT UNSIGNED NOT NULL,
  PRIMARY KEY (CLI_CODIGO),
  FOREIGN KEY (CLI_BAI_CODIGO) REFERENCES TB_BAIRROS (BAI_CODIGO)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_TELEFONES_CLIENTES
-- -----------------------------------------------------
CREATE TABLE TB_TELEFONES_CLIENTES (
  TDC_CLI_CODIGO INT UNSIGNED NOT NULL,
  TDC_TELEFONE VARCHAR(20) NOT NULL,
  PRIMARY KEY (TDC_CLI_CODIGO, TDC_TELEFONE), -- Criação de uma chave primária composta
FOREIGN KEY (TDC_CLI_CODIGO) REFERENCES TB_CLIENTES (CLI_CODIGO) 
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_FUNCIONARIOS
-- -----------------------------------------------------
CREATE TABLE TB_FUNCIONARIOS (
  FUN_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  FUN_FUNCIONARIO VARCHAR(50) NOT NULL,
  FUN_DATA_ADMISSAO DATE NOT NULL,
  FUN_DATA_DEMISSAO DATE DEFAULT NULL,
PRIMARY KEY (FUN_CODIGO) 
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table TB_LOCACOES
-- -----------------------------------------------------
CREATE TABLE TB_LOCACOES (
  LOC_CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
  LOC_DATA_LOCACAO DATE NOT NULL,
  LOC_DATA_ENTREGA DATE,
  LOC_CAR_CODIGO INT UNSIGNED NOT NULL,
  LOC_CLI_CODIGO INT UNSIGNED NOT NULL,
  LOC_FUN_CODIGO INT UNSIGNED NOT NULL,
  PRIMARY KEY (LOC_CODIGO) ,
  FOREIGN KEY (LOC_CAR_CODIGO) REFERENCES TB_CARROS (CAR_CODIGO),
  FOREIGN KEY (LOC_CLI_CODIGO) REFERENCES TB_CLIENTES (CLI_CODIGO),
  FOREIGN KEY (LOC_FUN_CODIGO) REFERENCES TB_FUNCIONARIOS (FUN_CODIGO)
) ENGINE = InnoDB;

------------------------------------------------------
-- ALTERAÇÔES
------------------------------------------------------

ALTER TABLE TB_MARCAS ADD CONSTRAINT CON_MARCA_UNIQUE UNIQUE (MAR_MARCA);
ALTER TABLE TB_CORES ADD CONSTRAINT CON_COR_UNIQUE UNIQUE (COR_COR);
ALTER TABLE TB_ESTADOS_CONSERVACAO ADD CONSTRAINT CON_ESTADO_UNIQUE UNIQUE (EST_ESTADO);
ALTER TABLE TB_CLIENTES ADD COLUMN CLI_DOCUMENTO VARCHAR(20) UNIQUE NOT NULL;
ALTER TABLE TB_CLIENTES ADD COLUMN CLI_EMAIL VARCHAR(50) UNIQUE NOT NULL;
ALTER TABLE TB_CLIENTES ADD COLUMN CLI_ENDERECO VARCHAR(100) NOT NULL;
ALTER TABLE TB_CARROS ADD COLUMN CAR_KM INT NOT NULL;
ALTER TABLE TB_CARROS ADD CONSTRAINT CON_KM_NEGATIVO CHECK (CAR_KM > 0);
ALTER TABLE TB_CARROS ADD CONSTRAINT CON_ANO_NEGATIVO CHECK (CAR_ANO > 0);
ALTER TABLE TB_LOCACOES ADD COLUMN LOC_ODOMETRO_INICIAL INT NOT NULL;
ALTER TABLE TB_LOCACOES ADD COLUMN LOC_ODOMETRO_FINAL INT NOT NULL;

CREATE VIEW VW_CLIENTES AS
SELECT CLI_CODIGO, CLI_NOME, CLI_DOCUMENTO, CLI_EMAIL, CLI_ENDERECO, BAI_BAIRRO
FROM TB_CLIENTES
INNER JOIN TB_BAIRROS ON CLI_BAI_CODIGO = BAI_CODIGO;

CREATE VIEW VW_CARROS AS
SELECT CAR_CODIGO, CAR_MODELO, CAR_ALUGUEL, CAR_KM, CAR_DISPONIVEL, COR_COR, MAR_MARCA, EST_ESTADO
FROM TB_CARROS
INNER JOIN TB_CORES ON CAR_COR_CODIGO = COR_CODIGO
INNER JOIN TB_MARCAS ON CAR_MAR_CODIGO = MAR_CODIGO
INNER JOIN TB_ESTADOS_CONSERVACAO ON CAR_EST_CODIGO = EST_CODIGO;

CREATE VIEW VW_LOCACOES AS
SELECT LOC_CODIGO, LOC_DATA_LOCACAO, LOC_DATA_ENTREGA, CAR_MODELO, CLI_NOME, FUN_FUNCIONARIO
FROM TB_LOCACOES
INNER JOIN TB_CARROS ON LOC_CAR_CODIGO = CAR_CODIGO
INNER JOIN TB_CLIENTES ON LOC_CLI_CODIGO = CLI_CODIGO
INNER JOIN TB_FUNCIONARIOS ON LOC_FUN_CODIGO = FUN_CODIGO;
